### ISSUE TITLE
Unable to fold or hide sidebar once it is activated

### ISSUE THREAD

**Issue by mine2chow** [patrys/vscode-code-outline#102]
Because of the new auto reveal function, Once activated the sidebar after boot, it can not be folded or hidden any more, expanding automatically when the selection changed.

**Comment by rdlaner** [comment]
This is really annoying! I have to constantly restart VSCode in order to hide the sidebar.

**Comment by racedaemon** [comment]
I found this in the release notes. 

"By default, the item to be revealed is selected. In order to not select the item, set the select option to false. For example:

  customView.reveal('element', { select: false });   "

The description seems a little confusing. I suppose they should use the word "focus" instead of "select". Because once the element is "revealed" it is in view. But one might think the element needs to be selected.

I'm talking semantics here. Not sure how the API works. But it is highly probable that "select" has to be "false".

**Comment by ricpol** [comment]
See also #103, #107... Thanks for the workaround!

**Comment by patrys** [comment]
I've opened [an upstream issue](https://github.com/Microsoft/vscode/issues/48198) to track this.
