### ISSUE TITLE
Forced to be focus to editor view

### ISSUE THREAD

**Issue by iwaseyusuke** [patrys/vscode-code-outline#104]
Hi! I'm a big fan of this extension!

But... seems to be related to https://github.com/patrys/vscode-code-outline/issues/12, when I'm [viewing diffs](https://code.visualstudio.com/docs/editor/versioncontrol#_viewing-diffs), forced to be back to editor view due to jumping to symbols automatically.

Is it expected behavior?

Thanks

**Comment by patrys** [comment]
It's a bug, I'll try to solve this in the next couple of days. If you have time to find a proper solution I'd be glad to merge a pull request!

**Comment by efc** [comment]
It seems that if the code outline is not visible on the screen then the highlighting of the symbols should be disabled. This bug is not just with diffs, but also occurs while stepping during debugging or while clicking on a search result in the project search results.

**Comment by efc** [comment]
After a bit of digging, this change to `symbolOutline.js` kind of works for me...

    vscode_1.window.onDidChangeTextEditorSelection(event => {
        if (event.kind && event.kind != 3) {
            if (event.selections.length) {
                const node = treeDataProvider.getNodeByPosition(event.selections[0].active);
                if (node) {
                    this.symbolViewer.reveal(node);
                }
            }
        }
    });

I actually don't know how to work with the `.ts` file, but I imagine the same change there would have a similar impact. The number 3 is actually the enumerator [TextEditorSelectionChangeKind.Command](https://www.dartdocs.org/documentation/vscode/1.0.0/vscode/TextEditorSelectionChangeKind-class.html), though I'm also not clear on how to use that.

The basic idea is to only reveal the symbol if the editor selection was made by keyboard or mouse, not if it is by command or undefined.

This code produces an error when you click on a symbol with the search results sidebar visible (or anything other than the sidebar with the outline, really). But since I only see that error when looking at the developer console, the end result is still better than the bug for me.

I still think it would make more sense to only reveal the symbols when the sidebar with the code outline is visible, but I could not figure out how to find that.

**Comment by alexclst** [comment]
The code above does make things quite a bit better. However, it still is a bit buggy even with this code. After using search or debug (or any other feature that uses commands to move the cursor) then Code Outline won’t take over when you manually move around a file. But the moment you have the Explorer visible and manually move around a file, then switch to another sidebar, but don’t yet use commands to move the cursor (ie in the Source Control sidebar), Code Outline will again take over. The ideal fix for this would make Code Outline stay completely out of the way unless the Explorer is visible, regardless of what is causing the cursor to move around in a file.

**Comment by patrys** [comment]
If I don't find a better solution in the next couple of days, I'll move the reveal code to a command.

**Comment by iwaseyusuke** [comment]
@patrys Thanks! v0.1.1 works well as expected!

**Comment by efc** [comment]
Thanks for the update, @patrys!
