### ISSUE TITLE
Python - lambda function arguments recognized as module labels

### ISSUE THREAD

**Issue by ZlatSic** [patrys/vscode-code-outline#125]
If I create a python module with this line:
`lambda_set = {
    lambda x: print(x),
    lambda y: print(y),
    lambda z: print(z)
}`
I get a tree like this:
- lambda_set
- x
- y
- z

(where the all the names have the "module variable" icon next to them)
I'm not sure if this is because of the outline plugin or the Python extension is not recognizing the variables correctly, but x, y and z shouldn't be shown because they don't exist in the module scope, only in the scope of the lambdas that declare them.

**Comment by patrys** [comment]
The [Python extension](https://github.com/Microsoft/vscode-python) currently reports all variables including local ones and function parameters. It only reports their name as the definition scope which is why `x`, `y` and `z` are not contained within `lambda_set` as one might expect.

Please open issues in the Python extension repository if you have an idea on how these could be improved. Code Outline only takes what the plugin is returning and displays it as a tree, it does not know anything about any particular language.
