### ISSUE TITLE
Extension does not installed properly

### ISSUE THREAD

**Issue by yaboroda** [patrys/vscode-code-outline#132]
OS: archlinux
VS Code version: 1.23.1

I installed extension from marketplace. It didn't show any errors. But bar with symbols do not show in under explorer bar. 

Commands "Refresh code outline" and "Show in code outline" exists in F1 command line, but doesn't work. Appears errors:

command 'symbolOutline.refresh' not found
command 'symbolOutline.revealCurrentSymbol' not found

**Comment by patrys** [comment]
There should be a separate button in the sidebar, not under the Explorer tab.

**Comment by yaboroda** [comment]
True! I just keep it hidden and totally forgot about it existence ))
Thanks, it works perfectly.

**Comment by bsmithEG** [comment]
Yeah, but I think that means the Code Outline tasks need to be removed from the command palate, it's super confusing and generates those errors when used.

The context:  I didn't realize that there was a recent change to add code outline as a separate button, which in of itself is annoying (because I didn't really see anything in the doc), so I tried to uninstall/reinstall and then used the command palate to see two tasks:

"Refresh code outline"

**Comment by civerzhang** [comment]
@patrys my outline tab is also in the sidebar, what can I do to move the outline tab into Explorer tab? I have just upgraded my VSCode, it didn't work.
